# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ibasemployeeservice:
    image: ibasemployeeservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5069:5069
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
